FROM zabbix/zabbix-agent2:ubuntu-latest 

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    snmp \
    python3 python3-pip \
    net-tools \
    vim \
    && rm -rf /var/lib/apt/lists/*

ENV TZ=America/Recife
