services:
    oai-enb-2:
        image: oaisoftwarealliance/oai-enb:2024.w25
        privileged: true
        container_name: oai-enb-2
        
        entrypoint: /bin/sh -c "/opt/oai-enb/bin/uhd_images_downloader.py && /opt/oai-enb/bin/lte-softmodem -O /opt/oai-enb/etc/enb.conf"
        networks:
            public_net:
                ipv4_address: 192.168.61.30
                #expose:
                #- "10000"
        environment:
            TZ: Europe/Paris
            #USE_ADDITIONAL_OPTIONS: --ue-txgain 50 --ue-rxgain 40 --ue-fo-compensation --log_config.global_log_options level,nocolor,time
        volumes:
            - ../conf/n310PRB100_2.conf:/opt/oai-enb/etc/enb.conf
        healthcheck:
            test: /bin/bash -c "pgrep lte-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    private_net:
        name: rfsim4g-oai-private-net
        ipam:
            config:
                - subnet: 192.168.68.0/26
        driver_opts:
            com.docker.network.bridge.name: "rfsim4g-private"
    public_net:
        name: rfsim4g-oai-public-net
        ipam:
            config:
                - subnet: 192.168.61.0/26
        driver_opts:
            com.docker.network.bridge.name: "rfsim4g-public-2"
            
